apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-mysql
  template:
    metadata:
      labels:
        app: employee-mysql
    spec:
      initContainers:
        - name: mysql-init
          image: busybox
          command: ['sh', '-c', 'cp /init-sql/init.sql /docker-entrypoint-initdb.d/']
          volumeMounts:
            - name: mysql-init
              mountPath: /init-sql
            - name: mysql-storage
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.dbName }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.user }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.password }}"
          ports:
            - containerPort: {{ .Values.mysql.port }}
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-storage
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-storage
          emptyDir: {}
        - name: mysql-init
          configMap:
            name: mysql-init-script
