server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://employee-mysql:3306/employeedb}
    username: ${SPRING_DATASOURCE_USERNAME:empuser}
    password: ${SPRING_DATASOURCE_PASSWORD:EmpPass123!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
